(EvaluationLink (stv 1 1)
  (PredicateNode "ER")
  (PatientNode "441786"))
(EvaluationLink (stv 1 1)
  (PredicateNode "PR")
  (PatientNode "491272"))
(EvaluationLink (stv 1 1)
  (PredicateNode "tumor")
  (ListLink
    (PatientNode "411351")
    (ConceptNode "T2")))
(EvaluationLink (stv 1 1)
  (PredicateNode "tumor")
  (ListLink
    (PatientNode "36825")
    (ConceptNode "T2")))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "809225")
    (ConceptNode "k2")))
(EvaluationLink (stv 0 1)
  (PredicateNode "ER")
  (PatientNode "411351"))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "615328")
    (ConceptNode "LumA")))
(EvaluationLink (stv 1 1)
  (PredicateNode "node")
  (PatientNode "411351"))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "36792")
    (ConceptNode "LumB")))
(EvaluationLink (stv 0 1)
  (PredicateNode "HER2")
  (PatientNode "809225"))
(EvaluationLink (stv 1 1)
  (PredicateNode "node")
  (PatientNode "809225"))
(EvaluationLink (stv 1 1)
  (PredicateNode "tumor")
  (ListLink
    (PatientNode "615328")
    (ConceptNode "T4")))
(EvaluationLink (stv 0 1)
  (PredicateNode "HER2")
  (PatientNode "615328"))
(EvaluationLink (stv 0 1)
  (PredicateNode "PR")
  (PatientNode "809225"))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "809225")
    (ConceptNode "LumB")))
(EvaluationLink (stv 0 1)
  (PredicateNode "PR")
  (PatientNode "508549"))
(EvaluationLink (stv 1 1)
  (PredicateNode "tumor")
  (ListLink
    (PatientNode "491272")
    (ConceptNode "T1")))
(EvaluationLink (stv 1 1)
  (PredicateNode "PR")
  (PatientNode "615328"))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "411351")
    (ConceptNode "k2")))
(EvaluationLink (stv 1 1)
  (PredicateNode "ER")
  (PatientNode "491272"))
(EvaluationLink (stv 0 1)
  (PredicateNode "ER")
  (PatientNode "809225"))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "441786")
    (ConceptNode "LumA")))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "36825")
    (ConceptNode "LumA")))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "491272")
    (ConceptNode "LumA")))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "615328")
    (ConceptNode "k3")))
(EvaluationLink (stv 1 1)
  (PredicateNode "PR")
  (PatientNode "36825"))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "491272")
    (ConceptNode "k5")))
(EvaluationLink (stv 0 1)
  (PredicateNode "node")
  (PatientNode "36825"))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "36825")
    (ConceptNode "k1")))
(EvaluationLink (stv 1 1)
  (PredicateNode "node")
  (PatientNode "441878"))
(EvaluationLink (stv 1 1)
  (PredicateNode "tumor")
  (ListLink
    (PatientNode "508549")
    (ConceptNode "T2")))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "441669")
    (ConceptNode "k1")))
(EvaluationLink (stv 1 1)
  (PredicateNode "tumor")
  (ListLink
    (PatientNode "809225")
    (ConceptNode "T2")))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "36792")
    (ConceptNode "k4")))
(EvaluationLink (stv 1 1)
  (PredicateNode "node")
  (PatientNode "441786"))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "508549")
    (ConceptNode "k2")))
(EvaluationLink (stv 0 1)
  (PredicateNode "ER")
  (PatientNode "508549"))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "441878")
    (ConceptNode "k2")))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "411351")
    (ConceptNode "Her2")))
(EvaluationLink (stv 0 1)
  (PredicateNode "node")
  (PatientNode "441669"))
(EvaluationLink (stv 0 1)
  (PredicateNode "HER2")
  (PatientNode "491272"))
(EvaluationLink (stv 1 1)
  (PredicateNode "tumor")
  (ListLink
    (PatientNode "36792")
    (ConceptNode "T1")))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "508549")
    (ConceptNode "Basal")))
(EvaluationLink (stv 1 1)
  (PredicateNode "HER2")
  (PatientNode "411351"))
(EvaluationLink (stv 0 1)
  (PredicateNode "HER2")
  (PatientNode "508549"))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "441669")
    (ConceptNode "LumA")))
(EvaluationLink (stv 1 1)
  (PredicateNode "node")
  (PatientNode "615328"))
(EvaluationLink (stv 1 1)
  (PredicateNode "ER")
  (PatientNode "441669"))
(EvaluationLink (stv 1 1)
  (PredicateNode "ER")
  (PatientNode "441878"))
(EvaluationLink (stv 1 1)
  (PredicateNode "ER")
  (PatientNode "36825"))
(EvaluationLink (stv 1 1)
  (PredicateNode "node")
  (PatientNode "491272"))
(EvaluationLink (stv 1 1)
  (PredicateNode "ER")
  (PatientNode "615328"))
(EvaluationLink (stv 1 1)
  (PredicateNode "pam_coincide")
  (ListLink
    (PatientNode "441878")
    (ConceptNode "LumA")))
(EvaluationLink (stv 0 1)
  (PredicateNode "node")
  (PatientNode "36792"))
(EvaluationLink (stv 1 1)
  (PredicateNode "p5")
  (ListLink
    (PatientNode "441786")
    (ConceptNode "k1")))
(EvaluationLink (stv 1 1)
  (PredicateNode "ER")
  (PatientNode "36792"))
